---
title: "Bias in EPSRC Peer Review - Research Question 10"
author: 'Contributors: Ged Hiscoke & Dakota Langhals, Royal Statistical Society'
date: "Version: `r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  html_document:
    code_folding: hide
    toc_float: yes
  pdf_document: default
  word_document:
    reference_docx: C:/Users/GedHiscoke/Desktop/r_style_template.docx
    highlight: null
subtitle: 'Status: Final'
---

```{r setup, include=FALSE}

##Universal Document settings
knitr::opts_chunk$set(echo = TRUE, fig.width = 12, fig.height = 12, warning = FALSE, message = FALSE)


## Libraries
library(dplyr)      # For tidy coding
library(kableExtra) # For tables
library(ggplot2)    # For plotting
library(patchwork)  # For plot displays
library(tidyr)      # For tidy coding
library(ggforce)    # For tidy labelling on plots 
library(gridExtra)  # For display of joint plots
library(knitr)
library(openxlsx)   # for saving tables as excel files
library(scales)     # For commas in plot labels
library(boot)
library(rstatix)
library(DescTools)
library(ggridges)
library(cowplot)







## Set key file locations
## Directory for saving local high resolution copies of plots etc
data_folder_path    <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Datasets/"
note_folder_path    <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Notes/"
figure_folder_path  <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note10"
table_folder_path   <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Tables/Note10"



## Set key file names
raw_data_file       <- "PROJ2023.002-DATA001.xlsx"
BaselineEnvironment <- "PROJ2023.002 Environment - BASELINE.RData"
CleanedEnvironment  <- "PROJ2023.002 Environment - CLEANED.RData"
Sample20Environment <- "PROJ2023.002 Environment - SAMPLE20.RData"
Sample80Environment <- "PROJ2023.002 Environment - SAMPLE80.RData"
cleanedExcelFile    <- "PROJ2023.002-DATA002.xlsx"
WorkingEnvironment  <- "PROJ2023.002 Environment - WORKING.RData"
UKLFdata            <- "PROJ2023.002-DATA004.xlsx"


## Load needed data
load(file = file.path(data_folder_path, WorkingEnvironment))



## Define the RSS colour palette
RRSSgold      <- "#D3A41B" 
RSSblue       <- "#004B6D" 
RSSred        <- "#cc0000" 
RSStaupe      <- "#a6a086" 
RSSgreen      <- "#009933" 
RSSpurple     <- "#7879b9" 
RSSdark       <- "#393f4d" 
RSSlightblue    <- "#6db4c0" 
RSSseablue       <- "#287fc3" 
RSSorange     <- "#d86027"
RSSlightgrey  <- "#bdbdbd"
RSSmidgrey    <- "#939393"
RSSdarkkgrey  <- "#7e7e7e"
RSSjungle     <- "#1f3d0c"
RSSmint       <- "#5C9090" 
RSSherb       <- "#689E88"
RSSbright     <- "#8D31A4"
RSSlime       <- "#7DCF7A"
RSSviolet     <- "#614182"


##Variable specific colours
col_male      <- "#004b6d"
col_female    <- "#a6700a"
col_uk        <- "#393f4d"
col_nonuk     <- "#614182"
col_dis       <- "#005b49"
col_nodis     <- "#8e8e00"
col_white     <- "#7f3c21"
col_ethmin    <- "#3a3877"
col_unknown   <- "#bdbdbd"
col_notdisclosed  <- "#640106"
col_age1 <- "#b6d6b3"
col_age2 <- "#87bd00"
col_age3 <- "#299907"
col_age4 <- "#146f03"
col_age5 <- "#054907"
col_age6 <- "#0f2808"
col_eth1 <- "#a7a7c1"
col_eth2 <- "#74749d"
col_eth3 <- "#1e3399"
col_eth4 <- "#090771"
col_eth5 <- "#37163e"
col_eth6 <- "#59095f"
col_eth7 <- "#34086e"
```

# {.tabset}

## Data preparation {.tabset}

```{r data_prep}
Q10data.df <- EPSRC$PI.df
Q10data.df <- Q10data.df %>%
  mutate(BinarySuccess = ifelse(GrantOutcome == "Funded", "Funded", "Not Funded"))

```

```{r}
# function to Round tables -------------------------------------------

# Function to round columns as specified
round_columns <- function(df) {
  df <- df %>%
    mutate(
      Count = ifelse(Count < 6, "\u22645", round(Count / 5) * 5),
      across(where(is.numeric) & !c(Count), ~ ifelse(Count == "\u22645", "~", round(., 1)))
    )
  return(df)
}


```

## Confidence Intervals for Award Rate Within Each Region

```{r}
df <- Q10data.df

# Award Rate CI ---------------------------------------------------------



# Function to calculate bootstrap CI for proportions
boot_ci <- function(data, indices) {
  sampled_data <- data[indices]
  prop <- mean(sampled_data)
  return(prop)
}

# Function to compute bootstrapped confidence intervals
compute_ci <- function(data) {
  if (length(data) < 2) {
    return(data.frame(CI_Lower = NA, CI_Upper = NA))
  }
  
  boot_result <- boot(data, boot_ci, R = 1000)
  ci <- boot.ci(boot_result, type = "basic")
  return(data.frame(CI_Lower = ci$basic[4], CI_Upper = ci$basic[5]))
}

# Generalized function to compute counts, proportions, and CIs by group and demographic
compute_statistics <- function(df, group_col, demo_col) {
  df <- df %>%
    rename(Group = !!sym(group_col), Demographic = !!sym(demo_col))
  
  groups <- unique(df$Group)
  results_list <- list()
  
  for (group in groups) {
    group_df <- df %>% filter(Group == group)
    
    result <- group_df %>%
      group_by(Demographic) %>%
      summarise(
        Count = n(),
        Proportion = Count / nrow(group_df)
      ) %>%
      ungroup() %>%
      rowwise() %>%
      mutate(
        CI = list(compute_ci(group_df$Demographic == Demographic)),
        CI_L = CI$CI_Lower,
        CI_U = CI$CI_Upper
      ) %>%
      select(-CI) %>%
      ungroup() %>%
      mutate(Theme = group)
    
    results_list[[group]] <- result
  }
  
  results_df <- bind_rows(results_list)
  results_df <- bind_rows(results_list) %>%
    mutate(Group = demo_col)
  
  return(results_df)
}

# Apply the generalized function and print the results

final_result <- compute_statistics(df, "AnonREG", "BinarySuccess")
final_result <- final_result %>% rename(Region = Theme) %>% 
  mutate(Count = round(Count / 10) * 10)

kable(final_result)
```

#### Plot of the Award Rate Confidence Intervals, for Each Region

```{r}
rate_plot <- ggplot(final_result %>% filter(Demographic == "Funded"), aes(x = Region, y = Proportion, color = Region)) +
  geom_point(position = position_dodge(width = 0.5), size = 4) +
  geom_errorbar(aes(ymin = CI_L, ymax = CI_U), 
                position = position_dodge(width =  0.5), 
                width = 0.2) +
  labs(title = "Rate of Successful Award Applications by Region",
       x = "Region",
       y = "Successful Award Rate") +
  coord_flip() +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 24, hjust = 0.5, margin = margin(b = 15), face = "bold"),
    axis.title.x = element_text(size = 20, margin = margin(t = 15), face = "bold", hjust = 0.5, color = "black"),
    axis.title.y = element_text(size = 20, margin = margin(r = 15), face = "bold", hjust = 0.5, color = "black"),
    plot.margin = margin(t = 20, r = 10, b = 10, l = 10),
    axis.text.x = element_text(size = 16, face = "bold", color = "black"),
    axis.text.y = element_text(size = 16, face = "bold", color = "black"),
    strip.text = element_text(size = 16, face = "italic"),
    panel.background = element_rect(fill = "white", color = NA),  # Set panel background to white
    plot.background = element_rect(fill = "white", color = NA),   # Set plot background to white
    #panel.grid.major = element_line(color = "gray90"),            # Optional: adjust grid color
    panel.grid.minor = element_blank()
)

print(rate_plot)


figure_folder_path  <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note10"

ggsave(filename = paste0(figure_folder_path, "/award_rate_by_region.png"), 
       plot = rate_plot, width = 12, height = 12, dpi = 600, bg = "white")

```

#### Confidence Intervals for the Mean Award Value for each Region

```{r}
# Award value CI-------------------------------------------------------------

# Filter data
df <- Q10data.df %>% filter(GrantOutcome == "Funded")

# Function to calculate the mean
mean_fun <- function(data, indices) {
  mean(data[indices])
}

# Function to calculate mean and CI using bootstrapping
bootstrap_ci <- function(data, n_bootstrap = 1000, conf_level = 0.95) {
  boot_result <- boot(data, mean_fun, R = n_bootstrap)
  boot_ci <- boot.ci(boot_result, type = "basic", conf = conf_level)
  list(mean = mean(data), 
       CI_lower = boot_ci$basic[4], 
       CI_upper = boot_ci$basic[5])
}

# Group by AnonREG and calculate mean and CI
results <- df %>%
  group_by(AnonREG) %>%
  summarise(
    mean_value = mean(AdjustedApplicationValue),
    CI = list(bootstrap_ci(AdjustedApplicationValue))
  ) %>%
  unnest_wider(CI)


kable(results)
```


## Combined Plot

```{r}
# First, merge the data frames to ensure they have the same levels for AnonREG
df_combined <- df %>%
  filter(AdjustedApplicationValue < 5 & !is.na(AnonREG)) %>%
  left_join(results %>% filter(!is.na(AnonREG)), by = "AnonREG")

# Create the ridges plot with mean points and confidence intervals overlaid
award_value_plots <- ggplot(df_combined, aes(x = AdjustedApplicationValue, y = AnonREG, fill = AnonREG)) +
  geom_density_ridges(alpha = 0.5) +
  # Overlay mean points
  geom_point(aes(x = mean_value, y = AnonREG, color = AnonREG), size = 4, position = position_nudge(y = 0.4)) +
  # Overlay confidence intervals as horizontal error bars
  geom_errorbarh(aes(xmin = CI_lower, xmax = CI_upper, y = AnonREG), color = RSSblue, height = 0.3, linewidth = 1, position = position_nudge(y = 0.4)) +
  scale_x_continuous(breaks = seq(0, max(df$AdjustedApplicationValue, na.rm = TRUE), by = 0.5)) +
  theme_ridges() + 
  theme(
    legend.position = "none",
    plot.title = element_text(size = 24, hjust = 0.5, margin = margin(b = 15), face = "bold"),
    axis.title.x = element_text(size = 20, margin = margin(t = 15), face = "bold", hjust = 0.5, color = "black"),
    axis.title.y = element_text(size = 20, margin = margin(r = 15), face = "bold", hjust = 0.5, color = "black"),
    plot.margin = margin(t = 20, r = 10, b = 10, l = 10),
    axis.text.x = element_text(size = 16, face = "bold", color = "black"),
    axis.text.y = element_text(size = 16, face = "bold", color = "black"),
    strip.text = element_text(size = 16, face = "italic"),
    panel.background = element_rect(fill = "white", color = NA),  # Set panel background to white
    plot.background = element_rect(fill = "white", color = NA),   # Set plot background to white
    #panel.grid.major = element_line(color = "gray90"),            # Optional: adjust grid color
    panel.grid.minor = element_blank()
  ) +

  labs(
    title = "Distributions and Means of Inflation-Adjusted Award\nValue < £5 million for Funded Applications by Region",
    x = "Adjusted Award Value (£ millions)",
    y = "Region"
  )

print(award_value_plots)

figure_folder_path  <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note10"

ggsave(filename = paste0(figure_folder_path, "/distributions_and_means_value_by_region.png"), 
       plot = award_value_plots, width = 12, height = 12, dpi = 600, bg = "white")

```


```{r}
## All plots combined
combined_plot <- plot_grid(award_value_plots, rate_plot, ncol = 1, align = "v", rel_widths = c(1, 1))

# Display the combined plot
combined_plot

figure_folder_path  <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note10"

ggsave(filename = paste0(figure_folder_path, "/all_combined_by_region.png"), 
       plot = combined_plot, width = 12, height = 12, dpi = 600, bg = "white")
```

