---
title: "Bias in EPSRC Peer Review - Organisation Analysis"
author: 'Contributors: Eugenie Hunsicker, Dakota Langhals'
date: "Version: `r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  html_document:
    code_folding: hide
    toc_float: yes
  pdf_document: default
  word_document:
    reference_docx: "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/r_style_template.docx"
    highlight: null
subtitle: 'Status: Final'
---

```{r setup, include=FALSE}

##Universal Document settings
knitr::opts_chunk$set(echo = TRUE, fig.width = 12, fig.height = 6, warning = FALSE, message = FALSE)

## Libraries
library(dplyr)      # For tidy coding
library(kableExtra) # For tables
library(ggplot2)    # For plotting
library(patchwork)  # For plot displays
library(tidyr)      # For tidy coding
library(ggforce)    # For tidy labeling on plots 
library(gridExtra)  # For display of joint plots
library(knitr)
library(openxlsx)   # for saving tables as excel files
library(scales)     # For commas in plot labels
library(readxl)
library(boot)




## Set key file locations
## Directory for saving local high resolution copies of plots etc
data_folder_path    <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Datasets/"
note_folder_path    <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Notes/"
figure_folder_path  <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note17"
table_folder_path   <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/TablesNote17/"



## Set key file names
raw_data_file       <- "PROJ2023.002-DATA001.xlsx"
BaselineEnvironment <- "PROJ2023.002 Environment - BASELINE.RData"
CleanedEnvironment  <- "PROJ2023.002 Environment - CLEANED.RData"
Sample20Environment <- "PROJ2023.002 Environment - SAMPLE20.RData"
Sample80Environment <- "PROJ2023.002 Environment - SAMPLE80.RData"
cleanedExcelFile    <- "PROJ2023.002-DATA002.xlsx"
WorkingEnvironment  <- "PROJ2023.002 Environment - WORKING.RData"
UKLFdata            <- "PROJ2023.002-DATA004.xlsx"


## Load needed data
load(file = file.path(data_folder_path, WorkingEnvironment))


## Define the RSS colour palette

RRSSgold      <- "#D3A41B" 
RSSblue       <- "#004B6D" 
RSSred        <- "#cc0000" 
RSStaupe      <- "#a6a086" 
RSSgreen      <- "#009933" 
RSSpurple     <- "#7879b9" 
RSSdark       <- "#393f4d" 
RSSlightblue    <- "#6db4c0" 
RSSseablue       <- "#287fc3" 
RSSorange     <- "#d86027"
RSSlightgrey  <- "#bdbdbd"
RSSmidgrey    <- "#939393"
RSSdarkkgrey  <- "#7e7e7e"
RSSjungle     <- "#1f3d0c"
RSSmint       <- "#5C9090" 
RSSherb       <- "#689E88"
RSSbright     <- "#8D31A4"
RSSlime       <- "#7DCF7A"
RSSviolet     <- "#614182"


##Variable specific colours
col_male      <- "#004b6d"
col_female    <- "#a6700a"
col_uk        <- "#393f4d"
col_nonuk     <- "#614182"
col_dis       <- "#005b49"
col_nodis     <- "#8e8e00"
col_white     <- "#7f3c21"
col_ethmin    <- "#3a3877"
col_unknown   <- "#bdbdbd"
col_notdisclosed  <- "#640106"
col_age1 <- "#b6d6b3"
col_age2 <- "#87bd00"
col_age3 <- "#299907"
col_age4 <- "#146f03"
col_age5 <- "#054907"
col_age6 <- "#0f2808"
col_eth1 <- "#a7a7c1"
col_eth2 <- "#74749d"
col_eth3 <- "#1e3399"
col_eth4 <- "#090771"
col_eth5 <- "#37163e"
col_eth6 <- "#59095f"
col_eth7 <- "#34086e"
```


# {.tabset}

## Data Preparation

```{r}
Apps.df <- EPSRC$PI.df

```


```{r}
Apps.df$AdjustedApplicationValue <- as.numeric(Apps.df$AdjustedApplicationValue)
Apps.df$BinaryOutcome <- ifelse(Apps.df$GrantOutcome == "Funded", "Funded", "Not_Funded")

ap_org_reg.df <- Apps.df 
```

## Success Rates by Number of Applications

```{r}
org_counts <- ap_org_reg.df %>%
  group_by(FYDecisionDate, AnonOrgG, BinaryOutcome) %>%
  summarise(
    values = sum(AdjustedApplicationValue, na.rm = TRUE),
    numbers = n(),
    .groups = 'drop'
  ) %>%
  pivot_wider(
    names_from = c(BinaryOutcome),
    values_from = c(values, numbers),
    values_fill = list(values = 0, numbers = 0)
  )

colnames(org_counts) <- gsub(" ", "_", colnames(org_counts))


success_rates <- org_counts %>%
  mutate(rate_by_number = numbers_Funded/(numbers_Funded + numbers_Not_Funded), rate_by_value = values_Funded/(values_Funded + values_Not_Funded))
         
success_rates$total_fund_ct <- success_rates$numbers_Funded + success_rates$numbers_Not_Funded


mean_success_rate <- mean(success_rates$rate_by_number)

 
```


```{r}
# Step 1: Calculate the overall mean success rate
total_applications <- sum(success_rates$total_fund_ct)
total_successes <- sum(success_rates$numbers_Funded)
p <- total_successes / total_applications
print(paste("Total Successes:", total_successes))
print(paste("Total Applications:", total_applications))
print(paste("Overall Mean Success Rate (p):", round(p, 4)))


# Step 2: Simulate expected success rates
num_simulations <- 10000

simulate_success_rates <- function(n_i, p, num_simulations) {
  successes <- rbinom(num_simulations, size = n_i, prob = p)
  success_rates <- successes / n_i
  return(success_rates)
}

simulated_data <- success_rates %>%
  rowwise() %>%
  mutate(
    simulated_rates = list(simulate_success_rates(total_fund_ct, p, num_simulations))
  ) %>%
  unnest(cols = c(simulated_rates))

library(splines)


# Aggregate simulated data
simulated_summary <- simulated_data %>%
  group_by(total_fund_ct) %>%
  summarize(
    mean_rate = mean(simulated_rates, na.rm = TRUE),
    lower_95 = quantile(simulated_rates, 0.025, na.rm = TRUE),
    upper_95 = quantile(simulated_rates, 0.975, na.rm = TRUE)
  )

# Fit smoothing splines
mean_spline <- smooth.spline(simulated_summary$total_fund_ct, simulated_summary$mean_rate, spar = 0.9)
lower_spline <- smooth.spline(simulated_summary$total_fund_ct, simulated_summary$lower_95, spar = 0.9)
upper_spline <- smooth.spline(simulated_summary$total_fund_ct, simulated_summary$upper_95, spar = 0.9)

# Create prediction data
x_seq <- seq(min(simulated_summary$total_fund_ct), max(simulated_summary$total_fund_ct), length.out = 100)
mean_pred <- predict(mean_spline, x_seq)
lower_pred <- predict(lower_spline, x_seq)
upper_pred <- predict(upper_spline, x_seq)

smoothed_summary <- data.frame(
  total_fund_ct = x_seq,
  mean_rate = mean_pred$y,
  lower_95 = lower_pred$y,
  upper_95 = upper_pred$y
)

success_rates <- success_rates %>% 
  mutate(FYDecisionDate = substr(FYDecisionDate, 1, 4)
         ) %>% 
  rename(Year = FYDecisionDate)

```


```{r}

# Plotting
plot <- ggplot(success_rates, aes(x = total_fund_ct, y = rate_by_number)) +
  geom_point(aes(color = Year),
             alpha = 0.9) +
  labs(
    title = "Rates of Funding Success vs Number of Proposals\nfrom Organisations, by Year",
    x = "Number of Proposals Submitted by an Organisation",
    y = "Rate of Successful Applications"
  ) +
  theme(panel.background = element_rect(fill = "white", color = NA),  # Set panel background to white
        plot.background = element_rect(fill = "white", color = NA),   # Set plot background to white
        #panel.grid.major = element_line(color = "gray90"),            # Optional: adjust grid color
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 24, hjust = 0.5, margin = margin(b = 15), face = "bold"),
        plot.title.position = "plot",
        axis.title.x = element_text(size = 20, margin = margin(t = 15), face = "bold"),
        axis.title.y = element_text(size = 20, margin = margin(r = 10), face = "bold"),
        plot.margin = margin(t = 20, r = 10, b = 10, l = 10),
        axis.text.x = element_text(size = 16, face = "bold", colour = "black"),
        axis.text.y = element_text(size = 16, face = "bold", colour = "black"),
        legend.position = "top",
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 18, face = "bold"),
    ) +

  geom_ribbon(
    data = smoothed_summary,
    aes(
      x = total_fund_ct,
      ymin = lower_95,
      ymax = upper_95,
      fill = "Expected Distribution"
    ),
    alpha = 0.3,
    inherit.aes = FALSE
  ) +
  geom_hline(yintercept = p, 
             linetype = "dashed", 
             color = RSSred,
             size = 1.2) +
  annotate(
    "text",
    x = max(success_rates$total_fund_ct),
    y = p,
    label = paste("Overall Mean Success Rate =", scales::percent(p, accuracy = 0.1)),
    hjust = 0.9,
    vjust = 2,
    color = RSSred,
    size = 5,
    face = "bold"
  ) +
  scale_y_continuous(labels = percent_format(accuracy = 2)) +
  scale_fill_manual(name = NULL, values = c("Expected Distribution" = RSSblue))

print(plot)

ggsave(filename = "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note08/organisation_success_rate_FOR_REPORT.png",
       plot = plot, width = 12, height = 12, dpi = 600)

```



## Number of times in top quartile (by funding success rates and funding value)

```{r}
org_counts = ap_org_reg.df %>%
          group_by(FYDecisionDate,AnonOrgG,BinaryOutcome) %>%
          summarise(
              values = sum(AdjustedApplicationValue, na.rm = TRUE),
              numbers = n()
          ) %>%
          pivot_wider(names_from = c(BinaryOutcome),values_from = c(values, numbers))
          
colnames(org_counts) <- gsub(" ", "_", colnames(org_counts))

success_rates <- org_counts %>%
  mutate(rate_by_number = numbers_Funded/(numbers_Funded + numbers_Not_Funded), rate_by_value = values_Funded/(values_Funded + values_Not_Funded))
         
```
     

```{r}
success_rates$total_fund_ct <- success_rates$numbers_Funded + success_rates$numbers_Not_Funded
 
```

```{r}
#number_of_unique_orgs
n_orgs = n_distinct(ap_org_reg.df$AnonOrgG)
```


```{r}
quartiles_by_year <- success_rates %>%
  group_by(FYDecisionDate)%>%
  mutate(quartile_by_number = ntile(rate_by_number,4),quartile_by_value = ntile(rate_by_value,4)) %>%
  select(FYDecisionDate, AnonOrgG, quartile_by_number, quartile_by_value) 

# quartile 5 indicates no proposals from that organisation were decided in that FY
quartiles_by_year[quartiles_by_year %>% is.na()]<-5
  
```

```{r}
quartile_by_number_persistence <- quartiles_by_year %>%
  select(AnonOrgG, FYDecisionDate, quartile_by_number) %>%
  pivot_wider(names_from = FYDecisionDate, values_from = c(quartile_by_number)) %>%
  rename(FY14_15 = `2014/2015`, FY15_16 = `2015/2016`, FY16_17 = `2016/2017`, FY17_18 = `2017/2018`, FY18_19 = `2018/2019`, FY19_20 = `2019/2020`, FY20_21 = `2020/2021`, FY21_22 = `2021/2022`, FY22_23 = `2022/2023`)%>%
  mutate(top_times = rowSums(across(starts_with("FY"), ~ . == 1), na.rm = TRUE)) %>%
  group_by(top_times)%>%
  summarise(freq_by_num = n())
```

```{r}
quartile_by_value_persistence <- quartiles_by_year %>%
  select(AnonOrgG, FYDecisionDate, quartile_by_value) %>%
  pivot_wider(names_from = FYDecisionDate, values_from = c(quartile_by_value)) %>%
  rename(FY14_15 = `2014/2015`, FY15_16 = `2015/2016`, FY16_17 = `2016/2017`, FY17_18 = `2017/2018`, FY18_19 = `2018/2019`, FY19_20 = `2019/2020`, FY20_21 = `2020/2021`, FY21_22 = `2021/2022`, FY22_23 = `2022/2023`)%>%
  mutate(top_times = rowSums(across(starts_with("FY"), ~ . == 1), na.rm = TRUE)) %>%
  group_by(top_times) %>%
  summarise(freq_by_val = n())
```



```{r}
n_org <- n_distinct(quartiles_by_year$AnonOrgG)
quart_by_ct_tab <- table(quartiles_by_year$FYDecisionDate, quartiles_by_year$quartile_by_number)
 
```


```{r}
tops.df <- quartile_by_value_persistence %>%
  left_join(quartile_by_number_persistence) %>%
  replace_na(list(freq_by_val = 0, freq_by_num = 0)) 

```

```{r}
c(tops.df$freq_by_num,tops.df$freq_by_val)
```

```{r}
count_list = 0:6
 
top_freq.df <- data.frame(
  times_in_Q1 = rep(count_list,2),
  freq = c(tops.df$freq_by_num,tops.df$freq_by_val),
  series = rep(c("by_num","by_val"),each=7)
 
)
```

```{r}
plot <- ggplot(top_freq.df, aes(x = times_in_Q1, y = freq,color = series,group = series)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
 # geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), width = 0.05) +  #### Leaving this in for future reference if necessary, but confidence intervals aren't currently comparable because not all organisations apply each year
  labs(title = "Number of Years in Which Institutions Appeared in Top\nSuccess Rate Quartile or Top Funding Amount Quartile", 
       x = "Times in Top Quartile", 
       y = "Number of Institutions",
       color = "Ranking Type") + 
  theme(  text = element_text(family = "Frutiger LT Std"),
          plot.title = element_text(size = 24, hjust = 0.5, margin = margin(b = 15), face = "bold"), # Center title, add space below
          axis.title.x = element_text(size = 22, margin = margin(t = 15), face = "bold", colour = "black"), # Add space above x-axis title
          axis.title.y = element_text(size = 22, margin = margin(r = 15), face = "bold", colour = "black"), # Add space to the right of y-axis title
          # plot.margin = margin(t = 20, r = 10, b = 10, l = 10), # Add extra space around the plot
          axis.text.x = element_text(size = 16, face = "bold", colour = "black"), # Make axis easier to read
          axis.text.y = element_text(size = 16, face = "bold", colour = "black"),  # Make axis easier to read
          plot.title.position = "plot",
          panel.background = element_rect(fill = "white"),
          strip.text = element_text(size = 16, face = "italic"),
          legend.position = "top",
          legend.text = element_text(size = 16),
          legend.title = element_text(size = 18, face = "bold")) + 
  scale_color_manual(values = c("by_num" = RSSblue, "by_val" = RSSred), 
                     labels = c("by_num" = "By number", "by_val" = "By value"))

# Display the plot 
print(plot)

ggsave(filename = "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note07/top_quartile_frequencies_by_org.png",
       plot = plot, width = 12, height = 12, dpi = 600)
```




## What is the concentration of funding in terms of the number of top funded institutions in each year that account for 50%, 75%, 90% of overall funding granted

```{r}
All_fund <- ap_org_reg.df %>%
  filter(BinaryOutcome == "Funded") %>%
  group_by(FYDecisionDate) %>%
  summarise(tot_val_yr = sum(AdjustedApplicationValue, na.rm = TRUE))
```


```{r}
Total_funding <- ap_org_reg.df %>%
  filter(BinaryOutcome == "Funded") %>%
  group_by(FYDecisionDate,AnonOrgG) %>%
  summarise(tot_val = sum(AdjustedApplicationValue, na.rm = TRUE)) %>%
  left_join(All_fund, by="FYDecisionDate") %>%
  mutate(prop_tot = tot_val/tot_val_yr) %>%
  select(AnonOrgG,FYDecisionDate,prop_tot) %>%
  pivot_wider(names_from = FYDecisionDate, values_from = prop_tot) %>%
  rename(FY14_15 = `2014/2015`, FY15_16 = `2015/2016`, FY16_17 = `2016/2017`, FY17_18 = `2017/2018`, FY18_19 = `2018/2019`, FY19_20 = `2019/2020`, FY20_21 = `2020/2021`, FY21_22 = `2021/2022`, FY22_23 = `2022/2023`)%>%
  replace_na(list(FY14_15 = 0, FY15_16 = 0, FY16_17 = 0, FY17_18 = 0, FY18_19 = 0, FY19_20 = 0, FY20_21 = 0, FY21_22 = 0, FY22_23 = 0)) %>%
  
  arrange(desc(FY14_15)) %>%
  mutate(cum_sum_14 = cumsum(FY14_15)) %>%
  mutate(top50_2014 = (cum_sum_14 - FY14_15) <= 0.5, top75_2014 = (cum_sum_14 - FY14_15) <= 0.75, top90_2014 = (cum_sum_14 - FY14_15) <= 0.9) %>%

  arrange(desc(FY15_16)) %>%
  mutate(cum_sum_15 = cumsum(FY15_16)) %>%
  mutate(top50_2015 = (cum_sum_15 - FY15_16) <= 0.5, top75_2015 = (cum_sum_15 - FY15_16) <= 0.75, top90_2015 = (cum_sum_15 - FY15_16) <= 0.9) %>%

  arrange(desc(FY16_17)) %>%
  mutate(cum_sum_16 = cumsum(FY16_17)) %>%
  mutate(top50_2016 = (cum_sum_16 - FY16_17) <= 0.5, top75_2016 = (cum_sum_16 - FY16_17) <= 0.75, top90_2016 = (cum_sum_16 - FY16_17) <= 0.9) %>%

  arrange(desc(FY17_18)) %>%
  mutate(cum_sum_17 = cumsum(FY17_18)) %>%
  mutate(top50_2017 = (cum_sum_17 - FY17_18) <= 0.5, top75_2017 = (cum_sum_17 - FY17_18) <= 0.75, top90_2017 = (cum_sum_17 - FY17_18) <= 0.9) %>%

  arrange(desc(FY18_19)) %>%
  mutate(cum_sum_18 = cumsum(FY18_19)) %>%
  mutate(top50_2018 = (cum_sum_18 - FY18_19) <= 0.5, top75_2018 = (cum_sum_18 - FY18_19) <= 0.75, top90_2018 = (cum_sum_18 - FY18_19) <= 0.9) %>%

  arrange(desc(FY19_20)) %>%
  mutate(cum_sum_19 = cumsum(FY19_20)) %>%
  mutate(top50_2019 = (cum_sum_19 - FY19_20) <= 0.5, top75_2019 = (cum_sum_19 - FY19_20) <= 0.75, top90_2019 = (cum_sum_19 - FY19_20) <= 0.9) %>%

  arrange(desc(FY20_21)) %>%
  mutate(cum_sum_20 = cumsum(FY20_21)) %>%
  mutate(top50_2020 = (cum_sum_20 - FY20_21) <= 0.5, top75_2020 = (cum_sum_20 - FY20_21) <= 0.75, top90_2020 = (cum_sum_20 - FY20_21) <= 0.9) %>%

  arrange(desc(FY21_22)) %>%
  mutate(cum_sum_21 = cumsum(FY21_22)) %>%
  mutate(top50_2021 = (cum_sum_21 - FY21_22) <= 0.5, top75_2021 = (cum_sum_21 - FY21_22) <= 0.75, top90_2021 = (cum_sum_21 - FY21_22) <= 0.9) %>%

  arrange(desc(FY22_23)) %>%
  mutate(cum_sum_22 = cumsum(FY22_23)) %>%
  mutate(top50_2022 = (cum_sum_22 - FY22_23) <= 0.5, top75_2022 = (cum_sum_22 - FY22_23) <= 0.75, top90_2022 = (cum_sum_22 - FY22_23) <= 0.9)
  
```

```{r}
logical_columns = c(
  "top50_2014", "top75_2014", "top90_2014",
  "top50_2015", "top75_2015", "top90_2015",
  "top50_2016", "top75_2016", "top90_2016",
  "top50_2017", "top75_2017", "top90_2017",
  "top50_2018", "top75_2018", "top90_2018",
  "top50_2019", "top75_2019", "top90_2019",
  "top50_2020", "top75_2020", "top90_2020",
  "top50_2021", "top75_2021", "top90_2021",
  "top50_2022", "top75_2022", "top90_2022"
)
```

```{r}
proportion_true <- Total_funding %>%
  summarise(across(all_of(logical_columns),~mean(.x,na.rm=TRUE)))
```

```{r}
df_long <- proportion_true %>% 
  pivot_longer( cols = everything(), names_to = c(".value", "year"), names_sep = "_" )
```

```{r}
df_long <- df_long %>% pivot_longer(cols = c(top50, top75, top90), names_to = "variable", values_to = "value") 

```

```{r}
plot <- ggplot(df_long, aes(x = year, y = value, color = variable, group = variable)) + 
  geom_line(size = 1) + 
  geom_point(size = 3) + 
  labs(title = "Proportion of Top Institutions Receiving at\nLeast 50% 75%, and 90% of Funding by Year", 
       x = "Year", y = "Proportion of Institutions", color = "Metrics") + 
  theme(  text = element_text(family = "Frutiger LT Std 47 Condensed Light"),
          plot.title = element_text(size = 24, hjust = 0.5, margin = margin(b = 15), face = "bold"), # Center title, add space below
          axis.title.x = element_text(size = 22, margin = margin(t = 15), face = "bold", colour = "black"), # Add space above x-axis title
          axis.title.y = element_text(size = 22, margin = margin(r = 15), face = "bold", colour = "black"), # Add space to the right of y-axis title
          # plot.margin = margin(t = 20, r = 10, b = 10, l = 10), # Add extra space around the plot
          axis.text.x = element_text(size = 16, face = "bold", colour = "black"), # Make axis easier to read
          axis.text.y = element_text(size = 16, face = "bold", colour = "black"),  # Make axis easier to read
          plot.title.position = "plot",
          panel.background = element_rect(fill = "white"),
          strip.text = element_text(size = 16, face = "italic"),
          legend.position = "top",
          legend.text = element_text(size = 16),
          legend.title = element_blank()
          ) + 
          scale_color_manual(values = c("top50" = RSSblue, "top75" = RSSgold, "top90" = RSSred), 
                             labels = c("level1" = "Label for Level 1", "level2" = "Label for Level 2"))


print(plot)


ggsave(filename = "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note07/funding_concentration_by_top_orgs.png",
       plot = plot, width = 12, height = 12, dpi = 600)
```
















