---
title: "Bias in EPSRC Peer Review - Research Question 7"
author: 'Contributors: Eugenie Hunsicker, Dakota Langhals'
date: "Version: `r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  html_document:
    code_folding: hide
    toc_float: yes
  pdf_document: default
  word_document:
    reference_docx: "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/r_style_template.docx"
    highlight: null
subtitle: 'Status: Final'
---

```{r setup, include=FALSE}

##Universal Document settings
knitr::opts_chunk$set(echo = TRUE, fig.width = 12, fig.height = 12, warning = FALSE, message = FALSE)

## Libraries
library(dplyr)      # For tidy coding
library(kableExtra) # For tables
library(ggplot2)    # For plotting
library(patchwork)  # For plot displays
library(tidyr)      # For tidy coding
library(ggforce)    # For tidy labelling on plots 
library(gridExtra)  # For display of joint plots
library(knitr)
library(openxlsx)   # for saving tables as excel files
library(scales)     # For commas in plot labels
library(readxl)

## Define the RSS colour palette

RSSgold      <- "#D3A41B" 
RSSblue       <- "#004B6D" 
RSSred        <- "#cc0000" 
RSStaupe      <- "#a6a086" 
RSSgreen      <- "#009933" 
RSSpurple     <- "#7879b9" 
RSSdark       <- "#393f4d" 
RSSlightblue    <- "#6db4c0" 
RSSseablue       <- "#287fc3" 
RSSorange     <- "#d86027"
RSSlightgrey  <- "#bdbdbd"
RSSmidgrey    <- "#939393"
RSSdarkkgrey  <- "#7e7e7e"
RSSjungle     <- "#1f3d0c"
RSSmint       <- "#5C9090" 
RSSherb       <- "#689E88"
RSSbright     <- "#8D31A4"
RSSlime       <- "#7DCF7A"
RSSviolet     <- "#614182"


##Variable specific colours
col_male      <- "#004b6d"
col_female    <- "#a6700a"
col_uk        <- "#393f4d"
col_nonuk     <- "#614182"
col_dis       <- "#005b49"
col_nodis     <- "#8e8e00"
col_white     <- "#7f3c21"
col_ethmin    <- "#3a3877"
col_unknown   <- "#bdbdbd"
col_notdisclosed  <- "#640106"
col_age1 <- "#b6d6b3"
col_age2 <- "#87bd00"
col_age3 <- "#299907"
col_age4 <- "#146f03"
col_age5 <- "#054907"
col_age6 <- "#0f2808"
col_eth1 <- "#a7a7c1"
col_eth2 <- "#74749d"
col_eth3 <- "#1e3399"
col_eth4 <- "#090771"
col_eth5 <- "#37163e"
col_eth6 <- "#59095f"
col_eth7 <- "#34086e"

## Set key file locations
## Directory for saving local high resolution copies of plots etc
data_folder_path    <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Datasets/"
note_folder_path    <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Notes/"
figure_folder_path  <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note17"
table_folder_path   <- "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/TablesNote17/"



## Set key file names
raw_data_file       <- "PROJ2023.002-DATA001.xlsx"
BaselineEnvironment <- "PROJ2023.002 Environment - BASELINE.RData"
CleanedEnvironment  <- "PROJ2023.002 Environment - CLEANED.RData"
Sample20Environment <- "PROJ2023.002 Environment - SAMPLE20.RData"
Sample80Environment <- "PROJ2023.002 Environment - SAMPLE80.RData"
cleanedExcelFile    <- "PROJ2023.002-DATA002.xlsx"
WorkingEnvironment  <- "PROJ2023.002 Environment - WORKING.RData"
UKLFdata            <- "PROJ2023.002-DATA004.xlsx"


## Load needed data
load(file = file.path(data_folder_path, WorkingEnvironment))

```

# {.tabset}

## Data Preparation

```{r}
df_0 <- EPSRC$Investigators.df %>% 
  filter(GrantOutcome == "Funded")
df_0$BinaryOutcome <- ifelse(df_0$GrantOutcome == "Funded", "Funded", "Not_Funded")
```

```{r}
matt_0 <- EPSRC$PI.df 
matt_0$BinaryOutcome <- ifelse(matt_0$GrantOutcome == "Funded", "Funded", "Not_Funded")
```

```{r}
fys = c("2014/2015", "2015/2016", "2016/2017", "2017/2018", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023")

roles = c("Fellow", "Principal_Investigator", "Co_Investigator")

```

```{r}
mattfys = fys[7:9]
```


```{r}
success_rates.fun <- function(data) {
  matt_success.boot <- data %>%
  group_by(BinaryOutcome, matthew) %>%
  summarise(count = n(), value = sum(AdjustedApplicationValue)) %>%
  pivot_wider(names_from = BinaryOutcome, values_from=c(count,value))
 
# fill in any na's in the resulting datset with 0
matt_success_2.boot <- levels.df %>%
  left_join(matt_success.boot,by = "matthew")
 
matt_success_2.boot[matt_success_2.boot %>% is.na()]<-0
 
# Calculate success rates by number and value for each group
matt_success_2.boot <- matt_success_2.boot %>%
  mutate(sr_by_ct = count_Funded/(`count_Not_Funded`+ count_Funded),
         sr_by_val = value_Funded/(`value_Not_Funded`+ value_Funded)
         )
  return(matt_success_2.boot)

matt_success$matthew <- factor(matt_success$matthew, levels = c("Fellow", "PI", "Co-I", "None"))
matt_success_2$matthew <- factor(matt_success_2$matthew, levels = c("Fellow", "PI", "Co-I", "None"))
}


```


```{r}
# Wrapper function for bootstrap 
matt_boot_wrapper <- function(data, indices) { 
  # Resample the data 
  resampled_data <- data[indices, ]
  # run the function
  sr = success_rates.fun(resampled_data)
  # Return the statistics 
  return(c(sr[sr$matthew == "Fellow",]$sr_by_ct,
           sr[sr$matthew == "PI",]$sr_by_ct,
           sr[sr$matthew == "Co-I",]$sr_by_ct,
           sr[sr$matthew == "None",]$sr_by_ct,
           sr[sr$matthew == "Fellow",]$sr_by_val,
           sr[sr$matthew == "PI",]$sr_by_val,
           sr[sr$matthew == "Co-I",]$sr_by_val,
           sr[sr$matthew == "None",]$sr_by_val
           )
  ) 
} 
```



```{r}
df <- df_0 %>%
  group_by(AnonINV, Role, FYDecisionDate) %>%
  summarise(count = n()) %>%
  mutate(success = count > 0) %>%
  pivot_wider(names_from = c(Role,FYDecisionDate), values_from = success) 

df[df %>% is.na()]<-FALSE
 
colnames(df) <- gsub(" ", "_", colnames(df))
```

```{r}
colnames = paste0(roles, sep = "_", fys[1])
newcol = paste0("outcome",sep = "_", fys[1])
df %>% 
  mutate(!!newcol := case_when(
  !!sym(colnames[1]) ~ "Fellow",
  !!sym(colnames[2]) ~ "PI",
  !!sym(colnames[3]) ~ "Co-I",
  TRUE ~ "None"
  )
  )

```


```{r}
for(i in fys){
  colnames = paste0(roles, sep = "_",i)
  newcol = paste0("outcome",sep = "_",i)
  df <- df %>% 
    mutate(!!newcol := case_when(
    !!sym(colnames[1]) ~ "Fellow",
    !!sym(colnames[2]) ~ "PI",
    !!sym(colnames[3]) ~ "Co-I",
    TRUE ~ "None"
    )
    )
  }
```

```{r}
outcols = paste0("outcome",sep = "_", fys)
outcols = c("AnonINV",outcols)
df <- df %>%
  select(all_of(outcols))
```


```{r}
matthew.df <- matt_0 %>%
  left_join(df,by = "AnonINV") %>% 
  mutate_at(vars(all_of(outcols)), ~replace(., is.na(.), "None"))
  
```



```{r, message = FALSE}
levels.df <- data.frame(matthew = c("Fellow","PI","Co-I","None"))
fel_sr_val = c()
fel_sr_ct = c()
pi_sr_val = c()
pi_sr_ct = c()
coi_sr_val = c()
coi_sr_ct = c()
none_sr_val = c()
none_sr_ct = c()


lower_ci_fel_val = c()
upper_ci_fel_val = c()
lower_ci_pi_val = c()
upper_ci_pi_val = c()
lower_ci_coi_val = c()
upper_ci_coi_val = c()
lower_ci_none_val = c()
upper_ci_none_val = c()
 
 
lower_ci_fel_ct = c()
upper_ci_fel_ct = c()
lower_ci_pi_ct = c()
upper_ci_pi_ct = c()
lower_ci_coi_ct = c()
upper_ci_coi_ct = c()
lower_ci_none_ct = c()
upper_ci_none_ct = c()


library(boot)

 
for(yr in mattfys){

index_yr <- which(fys == yr)
end_ind <- index_yr - 1
start_ind <- max(index_yr - 6,1)
prev_yrs <- fys[start_ind:end_ind]
cols_to_check = paste0("outcome",sep = "_",prev_yrs)

col_by_val_fel = paste("sr_fell_by_val",sep = "_", yr)
col_by_val_pi= paste("sr_pi_by_val",sep = "_", yr)
col_by_val_coi = paste("sr_coi_by_val",sep = "_", yr)
col_by_val_none = paste("sr_none_by_val",sep = "_", yr)

col_by_ct_fel = paste("sr_fell_by_ct",sep = "_", yr)
col_by_ct_pi= paste("sr_pi_by_ct",sep = "_", yr)
col_by_ct_coi = paste("sr_coi_by_ct",sep = "_", yr)
col_by_ct_none = paste("sr_none_by_ct",sep = "_", yr)

matthew_23.df <- matthew.df %>%
  filter(FYDecisionDate == yr) %>%
  mutate(matthew = case_when( 
    rowSums(across(all_of(cols_to_check), ~ . == "Fellow")) > 0 ~ "Fellow", 
    rowSums(across(all_of(cols_to_check), ~ . == "PI")) > 0 ~ "PI", 
    rowSums(across(all_of(cols_to_check), ~ . == "Co-I")) > 0 ~ "Co-I", 
    TRUE ~ "None" 
    ))

matthew_23.df$matthew <- factor(matthew_23.df$matthew, levels = c("Fellow", "PI", "Co-I", "None"))

matt_success <- matthew_23.df %>%
  group_by(BinaryOutcome, matthew) %>%
  summarise(count = n(), value = sum(AdjustedApplicationValue)) %>%
  pivot_wider(names_from = BinaryOutcome, values_from=c(count,value)) 

matt_success$matthew <- factor(matt_success$matthew, levels = c("Fellow", "PI", "Co-I", "None"))


matt_success_2 <- levels.df %>%
  left_join(matt_success,by = "matthew")

matt_success_2$matthew <- factor(matt_success_2$matthew, levels = c("Fellow", "PI", "Co-I", "None"))


matt_success_2[matt_success_2 %>% is.na()]<-0

matt_success_2 <- matt_success_2 %>%
  mutate(sr_by_ct = count_Funded/(count_Not_Funded + count_Funded),
         sr_by_val = value_Funded/(value_Not_Funded+ value_Funded)
         )
fel_sr_val = c(fel_sr_val,matt_success_2[matt_success_2 =="Fellow","sr_by_val"])
fel_sr_ct = c(fel_sr_ct, matt_success_2[matt_success_2 =="Fellow","sr_by_ct"])
pi_sr_val = c(pi_sr_val,matt_success_2[matt_success_2 =="PI","sr_by_val"])
pi_sr_ct = c(pi_sr_ct, matt_success_2[matt_success_2 =="PI","sr_by_ct"])
coi_sr_val = c(coi_sr_val,matt_success_2[matt_success_2 =="Co-I","sr_by_val"])
coi_sr_ct = c(coi_sr_ct,matt_success_2[matt_success_2 =="Co-I","sr_by_ct"])
none_sr_val = c(none_sr_val,matt_success_2[matt_success_2 =="None","sr_by_val"])
none_sr_ct = c(none_sr_ct,matt_success_2[matt_success_2 =="None","sr_by_ct"])

# Now bootstrap confidence intervals for each:
bootstrap_results_matt <- boot(data = matthew_23.df, statistic = matt_boot_wrapper, R = 1000) 

# Calculate the 95% confidence intervals
ci_fel_ct  <- boot.ci(bootstrap_results_matt, type = "perc", index = 1)
ci_pi_ct   <- boot.ci(bootstrap_results_matt, type = "perc", index = 2)
ci_coi_ct  <- boot.ci(bootstrap_results_matt, type = "perc", index = 3)
ci_none_ct <- boot.ci(bootstrap_results_matt, type = "perc", index = 4)

ci_fel_val <- boot.ci(bootstrap_results_matt, type = "perc", index = 5)
ci_pi_val  <- boot.ci(bootstrap_results_matt, type = "perc", index = 6)
ci_coi_val <- boot.ci(bootstrap_results_matt, type = "perc", index = 7)
ci_none_val<- boot.ci(bootstrap_results_matt, type = "perc", index = 8)

# # Display the results 
# #print(ci_ct)
 lower_ci_fel_val = c(lower_ci_fel_val,ci_fel_val$percent[4])
 upper_ci_fel_val = c(upper_ci_fel_val,ci_fel_val$percent[5])
lower_ci_pi_val = c(lower_ci_pi_val,ci_pi_val$percent[4])
upper_ci_pi_val = c(upper_ci_pi_val,ci_pi_val$percent[5])
lower_ci_coi_val = c(lower_ci_coi_val,ci_coi_val$percent[4])
upper_ci_coi_val = c(upper_ci_coi_val,ci_coi_val$percent[5])
lower_ci_none_val = c(lower_ci_none_val,ci_none_val$percent[4])
upper_ci_none_val = c(upper_ci_none_val,ci_none_val$percent[5])
# 
# 
lower_ci_fel_ct = c(lower_ci_fel_ct,ci_fel_ct$percent[4])
upper_ci_fel_ct = c(upper_ci_fel_ct,ci_fel_ct$percent[5])
lower_ci_pi_ct = c(lower_ci_pi_ct,ci_pi_ct$percent[4])
upper_ci_pi_ct = c(upper_ci_pi_ct,ci_pi_ct$percent[5])
lower_ci_coi_ct = c(lower_ci_coi_ct,ci_coi_ct$percent[4])
upper_ci_coi_ct = c(upper_ci_coi_ct,ci_coi_ct$percent[5])
lower_ci_none_ct = c(lower_ci_none_ct,ci_none_ct$percent[4])
upper_ci_none_ct = c(upper_ci_none_ct,ci_none_ct$percent[5])

}
```


## Plotting 

```{r}
# Put together resulting vectors in a dataframe
matthew_effect_val.df <- data.frame(
  funding_year = rep(mattfys,4),
  sr_val = c(fel_sr_val,pi_sr_val,coi_sr_val,none_sr_val),
  lower_ci = c(lower_ci_fel_val,lower_ci_pi_val, lower_ci_coi_val, lower_ci_none_val),
  upper_ci = c(upper_ci_fel_val,upper_ci_pi_val, upper_ci_coi_val, upper_ci_none_val),
  series = rep(c("fel_sr_val","pi_sr_val","coi_sr_val","none_sr_val"),each=length(mattfys))
)
```

```{r}
plot <- ggplot(matthew_effect_val.df, aes(x = funding_year, y = sr_val, color = series, group = series)) + 
  geom_point(size = 3, position = position_dodge(width = 0.3)) + 
  geom_line(size = 1, position = position_dodge(width = 0.3)) + 
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), width = 0.05, position = position_dodge(width = 0.3)) + 
  labs(
    title = "Percentage of Principal Investigator's Requested Funding Amounts\nAwarded, by Success History in Previous 6 Years", 
    x = "Funding year", 
    y = "Requested Funding Awarded"
  ) + 
  theme(
    panel.background = element_rect(fill = "white", color = NA),  
    plot.background = element_rect(fill = "white", color = NA),   
    panel.grid.minor = element_blank(),
    plot.title = element_text(size = 24, hjust = 0.5, margin = margin(b = 15), face = "bold"),
    plot.title.position = "plot",
    axis.title.x = element_text(size = 20, margin = margin(t = 15), face = "bold"),
    axis.title.y = element_text(size = 20, margin = margin(r = 10), face = "bold"),
    plot.margin = margin(t = 20, r = 10, b = 10, l = 10),
    axis.text.x = element_text(size = 16, face = "bold", colour = "black"),
    axis.text.y = element_text(size = 16, face = "bold", colour = "black"),
    legend.position = "top",
    legend.text = element_text(size = 16),
    legend.title = element_blank()
  ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1)) +
  scale_color_manual(
    values = c(
      "fel_sr_val" = RSSblue, 
      "pi_sr_val" = RSSred, 
      "coi_sr_val" = RSSgold, 
      "none_sr_val" = RSSgreen
    ), 
    labels = c(
      "fel_sr_val" = "Previously\nSuccessful Fellow",
      "pi_sr_val" = "Previously\nSuccessful PI", 
      "coi_sr_val" = "Previously\nSuccessful Co-I", 
      "none_sr_val" = "No Previous\nFunding Success"
    )
  )

 
# Display the plot 
print(plot)


ggsave(filename = "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note07/success_rate_by_value.png",
       plot = plot, width = 12, height = 12, dpi = 600)
```


```{r}
matthew_effect_ct.df <- data.frame(
  funding_year = rep(mattfys,4),
  sr_ct = c(fel_sr_ct,pi_sr_ct,coi_sr_ct,none_sr_ct),
  lower_ci = c(lower_ci_fel_ct,lower_ci_pi_ct, lower_ci_coi_ct, lower_ci_none_ct),
  upper_ci = c(upper_ci_fel_ct,upper_ci_pi_ct, upper_ci_coi_ct, upper_ci_none_ct),
  series = rep(c("fel_sr_ct","pi_sr_ct","coi_sr_ct","none_sr_ct"),each=length(mattfys))
)
```

```{r}
plot <- ggplot(matthew_effect_ct.df, aes(x = funding_year, y = sr_ct, color = series, group = series)) + 
  geom_point(size = 3, position = position_dodge(width = 0.3)) + 
  geom_line(size = 1, position = position_dodge(width = 0.3)) + 
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), width = 0.05, position = position_dodge(width = 0.3)) + 
  labs(
    title = "Percentage of Principal Investigator's Applications That Received\nFunding, by Success History in Previous 6 Years", 
    x = "Funding year", 
    y = "Success Rate"
  ) + 
  theme(
    panel.background = element_rect(fill = "white", color = NA),  
    plot.background = element_rect(fill = "white", color = NA),   
    panel.grid.minor = element_blank(),
    plot.title = element_text(size = 24, hjust = 0.5, margin = margin(b = 15), face = "bold"),
    plot.title.position = "plot",
    axis.title.x = element_text(size = 20, margin = margin(t = 15), face = "bold"),
    axis.title.y = element_text(size = 20, margin = margin(r = 10), face = "bold"),
    plot.margin = margin(t = 20, r = 10, b = 10, l = 10),
    axis.text.x = element_text(size = 16, face = "bold", colour = "black"),
    axis.text.y = element_text(size = 16, face = "bold", colour = "black"),
    legend.position = "top",
    legend.text = element_text(size = 16),
    legend.title = element_blank()
  ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1)) +
  scale_color_manual(
    values = c(
      "fel_sr_ct" = RSSblue, 
      "pi_sr_ct" = RSSred, 
      "coi_sr_ct" = RSSgold, 
      "none_sr_ct" = RSSgreen
    ), 
    labels = c(
      "fel_sr_ct" = "Previously\nSuccessful Fellow",
      "pi_sr_ct" = "Previously\nSuccessful PI", 
      "coi_sr_ct" = "Previously\nSuccessful Co-I", 
      "none_sr_ct" = "No Previous\nFunding Success"
    )
  )

 
# Display the plot 
print(plot)


ggsave(filename = "C:/Users/DakotaLanghals/OneDrive - Royal Statistical Society/PROJ2023.002 - Data folder DL Pickup/Draft Outputs/Images/Note07/success_rate_by_count.png",
       plot = plot, width = 12, height = 12, dpi = 600)

```






